spring.application.name=testcontainer-demo

#DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/db_test
spring.datasource.username=${POSTGRES_USER:123456}
spring.datasource.password=${POSTGRES_PASSWORD:123456}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SQL
spring.sql.init.mode=always